import type { APIRoute } from 'astro';
import { contentRepository } from '../../../config/site';
import { projectsListingToMarkdown } from '../../../core/services/markdown-twin';

export const prerender = true;

/**
 * Markdown twin of /pt/projects (V3d refinement addendum). The EN /projects listing has no twin
 * of its own (only individual /projects/[slug] pages do) — this is the first listing twin,
 * generated by `projectsListingToMarkdown` in markdown-twin.ts. Project entries themselves stay
 * EN-only content (V3d addendum decision, same as the PT HTML page: PT chrome, EN-titled cards).
 */
export const GET: APIRoute = async () => {
  const projects = await contentRepository.getProjects();

  return new Response(projectsListingToMarkdown(projects, 'pt-br'), {
    headers: { 'Content-Type': 'text/markdown; charset=utf-8' },
  });
};
